stages:
  - checks
  - test
  - build

variables:
  VITE_API_BASE_URL: "http://localhost"

checks:
  stage: checks
  image: node:latest
  needs: []
  script:
    - npm ci
    - npm run lint
    - npm run tsc

test:
  stage: test
  image: node:latest
  needs: []
  script:
    - npm ci
    - npm run test

build:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build
  needs:
    - checks
    - test
